### ISSUE TITLE
Everything breaks if IsLocal already exists in the animator as a bool (rework)

### ISSUE THREAD

**Issue by SenkyDragon** [regzo2/OSCmooth#26]
If IsLocal is already used as a boolean in the controller, OSCmooth should not add it as an additional float parameter as the duplicate parameter breaks the controller. If the type must be a float, and the controller already contains it as a bool, OSCsmooth MUST not only update the type of the existing parameter, it must also walk the entire controller (including sub-state machines) updating the type of every transition condition using IsLocal to swap it from a boolean condition to a float condition.

**Comment by SenkyDragon** [comment]
Issue reported by a user in the vrcfury discord.

**Comment by regzo2** [comment]
Will be fixed for release

**Comment by regzo2** [comment]
Fixed in c065d497baff43065916c890ca1e740549898802, will contextually use an existing IsLocal parameter to generate trees.
