### ISSUE TITLE
Config Saves Not Working

### ISSUE THREAD

**Issue by Adjerry91** [regzo2/OSCmooth#7]
Saving configs seam to be broken and trying to load into the config menu does not load.

**Comment by regzo2** [comment]
I will fix this as soon as I can.

**Comment by regzo2** [comment]
So strangely the configs saves properly, but on project reload they aren't instantiated for some odd reason? Gonna try to fix this before pushing a new release.

**Comment by Adjerry91** [comment]
More information on config bug. If you create new config on the same layer it will overwrite the something causing the other config to broken. When exporting the config will not import in new unity projects.

**Comment by Adjerry91** [comment]
When loading in unity project after creating the config save. There warning about the compile errors. 
![image](https://user-images.githubusercontent.com/58948489/204676694-11fbfaa0-e908-4c56-ab5f-b86319fddcaa.png)
The file seams okay if you create in Unity instance.
![image](https://user-images.githubusercontent.com/58948489/204676838-e59e414a-e98c-40fb-9a6e-93962507b538.png)
In the YAML file it seam to be missing FileID, could be a instance needs an id.
![image](https://user-images.githubusercontent.com/58948489/204677177-6005e08f-31ee-4365-8f7d-e0a79d44de87.png)

**Comment by regzo2** [comment]
Have discovered how to fix, I have to properly implement the serializable attributes to objects and have them be self-contained in their own file. Will make a patch for this soon.
